#!/usr/bin/env python3
"""Write updated CODEBASE_CONTEXT.md for the self-contained kernel ablation."""
import os

PP = "/home/sdubagun/work/repos/GEAK/outputs/eval_3kernels/topk/preprocess_selfcontained"

lines = [
    "# Codebase Context",
    "",
    "## File Layout",
    "",
    "This is a self-contained TopK kernel file. All code -- Triton JIT kernels,",
    "Python dispatch logic, and test harness -- is in a single file: kernel.py.",
    "",
    "```",
    "kernel.py   (855 lines)",
    "|-- Triton JIT Kernels (lines 1-340)",
    "|   |-- _topk_kernel          -- 1-stage kernel for small rows (M <= 1024)",
    "|   |-- topk_stage1_kernel    -- Stage 1: per-chunk top-k selection",
    "|   |-- _compare_and_swap     -- Bitonic sort building block",
    "|   |-- _bitonic_merge        -- Bitonic merge step",
    "|   |-- argsort               -- Full bitonic argsort",
    "|   |-- topk_stage2_kernel    -- Stage 2: merge chunk results via bitonic sort",
    "|",
    "|-- Python Dispatch Logic (lines 340-535)",
    "|   |-- _pick_block(m, k)     -- Block size selection (doubles from 128 to 1024)",
    "|   |-- one_stage_topk(x, k)  -- Launcher for 1-stage path (rows <= MAX_TINY_ROW)",
    "|   |       num_warps=4, num_stages=2 (hard-coded)",
    "|   |-- two_stage_topk(x, k)  -- Launcher for 2-stage path (large rows)",
    "|   |       chunk_size selection (256 or 1024)",
    "|   |       Stage 1 kernel launch -> Stage 2 kernel launch",
    "|   |-- MAX_TINY_ROW = 1024   -- Threshold: rows <= this use 1-stage, else 2-stage",
    "|   |-- topk(x, k, ...)       -- Main entry point / dispatcher",
    "|   |-- triton_op(x, k)       -- Benchmark wrapper calling topk()",
    "|   |-- torch_op(x, k)        -- PyTorch reference (torch.topk)",
    "|",
    "|-- Test Harness (lines 535-855)",
    "    |-- ALL_SHAPES (80 shapes) -- Full benchmark matrix",
    "    |-- HARNESS_SHAPES (25)    -- Uniformly sampled subset",
    "    |-- PROFILE_SHAPES (5)     -- Profiling subset",
    "    |-- run_correctness()      -- Validates against torch.topk",
    "    |-- run_profile()          -- Runs shapes for external profiler",
    "    |-- run_benchmark()        -- Timed benchmark with CUDA events, reports speedups",
    "    |-- __main__ CLI           -- --correctness, --profile, --benchmark, --full-benchmark",
    "```",
    "",
    "## Key Files",
    "",
    "| File | Role |",
    "|------|------|",
    "| kernel.py | TARGET KERNEL - edit this (contains JIT kernels + dispatch + harness) |",
    "",
    "## Architecture",
    "",
    "The TopK kernel uses two execution paths:",
    "",
    "1. **1-stage path** (rows <= MAX_TINY_ROW=1024): Single kernel launch per row.",
    "   Iteratively finds max, stores, masks out. O(M*K). Fast for small rows.",
    "",
    "2. **2-stage path** (rows > 1024): Two kernel launches.",
    "   - Stage 1 (topk_stage1_kernel): Splits row into chunks, finds top-k per chunk.",
    "     91.2% of total time (621us). Latency-bound, 2.8% HBM utilization.",
    "   - Stage 2 (topk_stage2_kernel): Merges chunk results via bitonic sort.",
    "     6.4% of time (43.6us). LDS bank conflicts.",
    "",
    "## Profiling Summary",
    "",
    "| Kernel | Duration | % Total | Bottleneck |",
    "|--------|----------|---------|------------|",
    "| topk_stage1_kernel (M=128256, chunk=1024) | 621us | 91.2% | Latency |",
    "| topk_stage2_kernel (k=8, N=1008, block=1024) | 43.6us | 6.4% | LDS |",
    "| _topk_kernel (M=128, K=8, block=128) | 9.0us | 1.3% | Latency |",
]

text = "\n".join(lines) + "\n"
path = os.path.join(PP, "CODEBASE_CONTEXT.md")
with open(path, "w") as f:
    f.write(text)
print(f"Wrote {path}: {len(text)} bytes, {len(lines)} lines")
