"""Helpers for excluding generated helper artifacts from patches.

GEAK runs often materialize temporary harness helpers, standalone benchmark
binaries, and wrapper scripts at the worktree root. Those artifacts should not
be treated as source patches, and can later break ``git apply`` during round
evaluation when they leak into patch capture.
"""

from __future__ import annotations

import subprocess
from fnmatch import fnmatch
from pathlib import Path, PurePosixPath

_ROOT_GENERATED_DIRS = {
    "build",
    "build_harness",
    ".aiter_jit",
    "_eval_worktree",
}

_ROOT_GENERATED_FILES = {
    "run.sh",
    "run_harness.sh",
    "test_harness.py",
    "rocprim_version.hpp",
    "CMakeCache.txt",
    "cmake_install.cmake",
    "Makefile",
    "_geak_eval_cmd.sh",
}

_ROOT_GENERATED_GLOBS = (
    "_geak_test_cmd_*.sh",
    "test*_harness.py",
    "test*_harness.cpp",
    "test_*_focused.py",
    "*_standalone",
    "*_standalone.cpp",
    "*_test",
    "*_test.exe",
    "*.bak",
    "*.o",
    "*.obj",
    "*.out",
    "*.bin",
)


def _normalize_rel_path(rel_path: str) -> str:
    return PurePosixPath(str(rel_path).lstrip("./")).as_posix()


def is_generated_helper_artifact(rel_path: str) -> bool:
    """Return True when *rel_path* looks like a GEAK-generated helper artifact.

    Matching is intentionally conservative and targets root-level helper files
    and helper build directories, not normal source files inside the repo tree.
    """

    rel = _normalize_rel_path(rel_path)
    if not rel:
        return False

    path = PurePosixPath(rel)
    parts = path.parts
    if not parts:
        return False

    if parts[0] in _ROOT_GENERATED_DIRS:
        return True

    if len(parts) != 1:
        return False

    name = parts[0]
    if name in _ROOT_GENERATED_FILES:
        return True

    return any(fnmatch(name, pattern) for pattern in _ROOT_GENERATED_GLOBS)


def generated_helper_excludes(cwd: Path | None = None) -> list[str]:
    """Return git/diff exclude patterns for generated helper artifacts."""

    excludes = [
        "run.sh",
        "run_harness.sh",
        "build",
        "build_harness",
        ".aiter_jit",
        "_eval_worktree",
        "test_harness.py",
        "test_harness_*.py",
        "test_harness_*.cpp",
        "rocprim_version.hpp",
        "_geak_test_cmd_*.sh",
        "_geak_eval_cmd.sh",
    ]
    if cwd is not None and cwd.is_dir():
        for child in cwd.iterdir():
            if is_generated_helper_artifact(child.name):
                excludes.append(child.name)
    # Stable order makes debugging easier.
    return sorted(dict.fromkeys(excludes))


def _parse_git_diff_paths(header: str) -> tuple[str, str] | None:
    """Extract ``(a_path, b_path)`` from a ``diff --git`` header."""

    prefix = "diff --git a/"
    if not header.startswith(prefix):
        return None
    remainder = header[len(prefix) :].rstrip("\n")
    separator = " b/"
    if separator not in remainder:
        return None
    a_path, b_path = remainder.split(separator, 1)
    return a_path, b_path


def strip_generated_helper_sections(patch_text: str) -> tuple[str, list[str]]:
    """Drop diff sections that touch generated helper artifacts.

    Returns ``(sanitized_patch_text, removed_paths)``. Only ``diff --git`` style
    sections are filtered; non-diff preamble is preserved.
    """

    if not patch_text.strip():
        return patch_text, []

    lines = patch_text.splitlines(keepends=True)
    preamble: list[str] = []
    sections: list[list[str]] = []
    current: list[str] | None = None

    for line in lines:
        if line.startswith("diff --git "):
            if current is not None:
                sections.append(current)
            current = [line]
            continue
        if current is None:
            preamble.append(line)
        else:
            current.append(line)

    if current is not None:
        sections.append(current)

    if not sections:
        return patch_text, []

    kept: list[str] = list(preamble)
    removed: list[str] = []
    for section in sections:
        parsed = _parse_git_diff_paths(section[0])
        if parsed is None:
            kept.extend(section)
            continue
        a_path, b_path = parsed
        if is_generated_helper_artifact(a_path) or is_generated_helper_artifact(b_path):
            removed.append(b_path or a_path)
            continue
        kept.extend(section)

    return "".join(kept), removed


def _normalize_patch_paths(patch_text: str, cwd: Path) -> str:
    """Rewrite absolute paths in a diff to be relative to cwd.

    Handles patches generated by ``diff -ruN /abs/path/a /abs/path/b``
    which produce ``--- /abs/.../kernel.py`` headers that ``git apply``
    cannot resolve.
    """
    import re as _re

    lines = patch_text.splitlines(keepends=True)
    out: list[str] = []
    for line in lines:
        # Rewrite --- a/absolute/path/to/kernel.py or --- /absolute/path
        if line.startswith(("--- ", "+++ ")):
            prefix = line[:4]
            rest = line[4:].rstrip("\n")
            # Strip timestamp from diff -ruN output
            rest = _re.sub(r"\t.*$", "", rest)
            # Remove a/ or b/ prefix
            if rest.startswith(("a/", "b/")):
                rest = rest[2:]
            # If path is absolute or deeply nested, keep only the filename
            p = Path(rest)
            if p.is_absolute() or len(p.parts) > 6:
                # Try to find the file in cwd
                for candidate in cwd.rglob(p.name):
                    rest = str(candidate.relative_to(cwd))
                    break
                else:
                    rest = p.name
            out.append(f"{prefix}{rest}\n")
        else:
            out.append(line)
    return "".join(out)


def apply_patch_with_generated_helper_fallback(
    *,
    patch_text: str,
    cwd: Path,
    env: dict[str, str] | None = None,
) -> tuple[subprocess.CompletedProcess[str], list[str]]:
    """Apply a git patch, retrying with path normalization and strip levels.

    Returns ``(result, removed_paths)``. When the patch only contained generated
    helper artifacts, the empty sanitized patch is treated as a successful no-op.
    """

    # Try 1: standard git apply
    result = subprocess.run(
        ["git", "apply", "--whitespace=nowarn", "--binary", "-"],
        cwd=str(cwd),
        input=patch_text,
        capture_output=True,
        text=True,
        env=env,
    )
    if result.returncode == 0:
        return result, []

    # Try 2: normalize absolute/deep paths to relative
    normalized = _normalize_patch_paths(patch_text, cwd)
    if normalized != patch_text:
        result2 = subprocess.run(
            ["git", "apply", "--whitespace=nowarn", "-p0", "-"],
            cwd=str(cwd),
            input=normalized,
            capture_output=True,
            text=True,
            env=env,
        )
        if result2.returncode == 0:
            return result2, []

    # Try 3: progressively strip more path components
    for strip in range(2, 8):
        result_strip = subprocess.run(
            ["git", "apply", "--whitespace=nowarn", f"-p{strip}", "-"],
            cwd=str(cwd),
            input=patch_text,
            capture_output=True,
            text=True,
            env=env,
        )
        if result_strip.returncode == 0:
            return result_strip, []

    # Try 4: strip generated helper artifacts
    sanitized_patch, removed_paths = strip_generated_helper_sections(patch_text)
    if not removed_paths:
        return result, []

    if not sanitized_patch.strip():
        noop = subprocess.CompletedProcess(
            args=["git", "apply", "--whitespace=nowarn", "--binary", "-"],
            returncode=0,
            stdout=result.stdout,
            stderr=result.stderr,
        )
        return noop, removed_paths

    retry = subprocess.run(
        ["git", "apply", "--whitespace=nowarn", "--binary", "-"],
        cwd=str(cwd),
        input=sanitized_patch,
        capture_output=True,
        text=True,
        env=env,
    )
    return retry, removed_paths
